from django.urls import path,include
from .views import *
urlpatterns = [
    
	path("policy/", policy, name="policy"),
	path("policy_edit/<pk>/", policy_edit, name="policy_edit"),
	path("policy_delete/<pk>/", policy_delete, name="policy_delete"),
	path("breach/", breach, name="breach"),
	path("breach_edit/<pk>/", breach_edit, name="breach_edit"),
	path("breach_delete/<pk>/", breach_delete, name="breach_delete"),
	path("staffpolicyacknowledgment/", staffpolicyacknowledgment, name="staffpolicyacknowledgment"),
	path("staffpolicyacknowledgment_edit/<pk>/", staffpolicyacknowledgment_edit, name="staffpolicyacknowledgment_edit"),
	path("staffpolicyacknowledgment_delete/<pk>/", staffpolicyacknowledgment_delete, name="staffpolicyacknowledgment_delete"),
	path("incident/", incident, name="incident"),
	path("incident_edit/<pk>/", incident_edit, name="incident_edit"),
	path("incident_delete/<pk>/", incident_delete, name="incident_delete"),
	path("correctiveaction/", correctiveaction, name="correctiveaction"),
	path("correctiveaction_edit/<pk>/", correctiveaction_edit, name="correctiveaction_edit"),
	path("correctiveaction_delete/<pk>/", correctiveaction_delete, name="correctiveaction_delete"),
	path("auditevidence/", auditevidence, name="auditevidence"),
	path("auditevidence_edit/<pk>/", auditevidence_edit, name="auditevidence_edit"),
	path("auditevidence_delete/<pk>/", auditevidence_delete, name="auditevidence_delete"),
	path("compliancecalendarevent/", compliancecalendarevent, name="compliancecalendarevent"),
	path("compliancecalendarevent_edit/<pk>/", compliancecalendarevent_edit, name="compliancecalendarevent_edit"),
	path("compliancecalendarevent_delete/<pk>/", compliancecalendarevent_delete, name="compliancecalendarevent_delete"),
	path("riskcontrolmatrix/", riskcontrolmatrix, name="riskcontrolmatrix"),
	path("riskcontrolmatrix_edit/<pk>/", riskcontrolmatrix_edit, name="riskcontrolmatrix_edit"),
	path("riskcontrolmatrix_delete/<pk>/", riskcontrolmatrix_delete, name="riskcontrolmatrix_delete"),
	path("compliancereturn/", compliancereturn, name="compliancereturn"),
	path("compliancereturn_edit/<pk>/", compliancereturn_edit, name="compliancereturn_edit"),
	path("compliancereturn_delete/<pk>/", compliancereturn_delete, name="compliancereturn_delete"),
	path("watchlistcheck/", watchlistcheck, name="watchlistcheck"),
	path("watchlistcheck_edit/<pk>/", watchlistcheck_edit, name="watchlistcheck_edit"),
	path("watchlistcheck_delete/<pk>/", watchlistcheck_delete, name="watchlistcheck_delete"),
]